---
- name: Deploy to Production Environment
  hosts: localhost
  gather_facts: false
  tasks:
    
    - name: context
      shell: pwd
      debugger: always
    
    - name: environment
      shell: echo $IMAGE_NAME
      debugger: always