---
- name: Deploy to Production Environment
  hosts: localhost
  gather_facts: false
  tasks:
    
    - name: context
      shell: pwd
      register: context
    
    - debug: var=context.stdout
    
    - name: environment
      shell: echo $IMAGE_NAME
      register: environment
    
    - debug: var=environment.stdout