---
name: Testa ansible execution
on: [push]
jobs:
    test-ansible:
        name: Test if ansible is working
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Test ansible
              run: ansible --version