---
name: Testa ansible execution
on: [push]
jobs:
    test-automation:
        name: Test working automation applications
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Test ansible
              run: ansible --version
            - name: Test terraform
              run: terraform --version 
    test-capabilities:
        name: Test another capabilities
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Check installed packages
              run: dpkg -l
            - name: Check environment variables
              run: env
            - name: Check path information
              run: |-
                pwd
                echo "---"
                ls -la
            - name: Check mount points information
              run: df -Th
