---
name: Testa ansible execution
on: [push]
jobs:
    test-ansible:
        name: Test working applications
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Test ansible
              run: ansible --version
            - name: Test terraform
              run: terraform --version
            - name: check installed packages
              run: dpkg -l
