---
name: Test actions ubuntu capabilities
on: [push]
jobs:
    test-automation:
        name: Test working applications
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: terra-kion
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Test ansible
              run: ansible --version
            - name: Test terraform
              run: terraform --version
            - name: Check installed packages
              run: dpkg -l
            - name: Check environment variables
              run: env
            - name: Check path information
              run: |-
                pwd
                echo "---"
                ls -la
            - name: Check mount points information
              run: df -Th
            - name: Check Tree on folder
              run: tree /home/runner/work/
            - name: GitHub Tag Name example
              run: |-
                echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
                echo "Tag name from github.ref_name: ${{  github.ref_name }}"
            - name: Execute Ansible Playbook
              run: |-
                ansible-playbook ansible-tests.yml